spring:
  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:redis}

  datasource:
    username: ${DB_USERNAME:backend}
    password: ${DB_PASSWORD:backend}
    url: jdbc:postgresql://${DB_HOST:postgres-local}:${DB_PORT:5432}/${DB_NAME:backend}

  flyway:
    schemas: ${DB_SCHEMA:public}
    user: ${DB_USERNAME:backend}
    password: ${DB_PASSWORD:backend}
    url: jdbc:postgresql://${DB_HOST:postgres-local}:${DB_PORT:5432}/${DB_NAME:backend}
    locations: classpath:db/migration/dev

  security:
    oauth2:
      client:
        provider:
          keycloak:
            jwk-set-uri: ${KC_ISSUER_URI:https://api.lockboxes.ru:8443/realms}/${KC_REALM:lockbox}/protocol/openid-connect/certs

keycloak:
  server-url: ${KC_SERVER:https://api.lockboxes.ru:8443}
  realm: ${KC_REALM:lockbox}
  client-id: ${KC_CLIENT_ID:web-back}
  client-secret: ${KC_CLIENT_SECRET:h3LyvVgQK7p2FIxpkKoKsecystFnZGC8}
  admin-username: ${KC_ADMIN_USERNAME:admin}
  admin-password: ${KC_ADMIN_PASSWORD:admin}
  max-pooled-per-route: ${KC_MAX_POOLED_PER_ROTE:50}
  connect-timeout: ${KC_CONNECTION_TIMEOUT:3000}
  read-timeout: ${KC_READ_TIMEOUT:5000}
  jwk-set-uri: ${KC_ISSUER_URI:https://api.lockboxes.ru:8443/realms}/${KC_REALM:lockbox}/protocol/openid-connect/certs

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    org.hibernate.tool.hbm2ddl: DEBUG

redis:
  host: ${REDIS_HOST:redis}
  port: ${REDIS_PORT:6379}