spring:
  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

  flyway:
    schemas: ${DB_SCHEMA}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

  security:
    oauth2:
      client:
        provider:
          keycloak:
            jwk-set-uri: ${KC_ISSUER_URI}/${KC_REALM}/protocol/openid-connect/certs